doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '18'
        charset: utf8
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Infra:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infra/Entity'
                prefix: 'Infra\Entity'
                alias: Infra

